baseURL = "https://jsonbruce.com"
title = "Max"
theme = "hugo-coder"
languageCode = "en"
defaultContentLanguage = "en"
hasCJKLanguage = true

paginate = 20
canonifyURLs = true

pygmentsStyle = "monokai"
pygmentsCodefences = true
pygmentsUseClasses  = false
pygmentsCodefencesGuessSyntax = true

googleAnalytics = "UA-140227175-1"
disqusShortname = ""

enableRobotsTXT = true
enableEmoji = true
enableGitInfo = true

[params]
    author = "Max Xu"
    info = "Full Stack Software Engineer"
    description = "Max Xu's personal website"
    keywords = "blog,software,engineer,developer,personal"
    avatarurl = "images/avatar.png"

    favicon_32 = "images/favicon-32x32.png"
    favicon_16 = "images/favicon-16x16.png"

    footercontent = ""

    hidecredits = false
    hidecopyright = false

    rtl = false

    math = true
    # custom_css = ["css/custom.css"]

    toc = true

# Social links
[[params.social]]
    name = "Github"
    icon = "fab fa-github fa-2x"
    weight = 1
    url = "https://github.com/jsonbruce/"
[[params.social]]
    name = "Gitlab"
    icon = "fab fa-gitlab fa-2x"
    weight = 2
    url = "https://gitlab.com/jsonbruce/"
[[params.social]]
    name = "Twitter"
    icon = "fab fa-twitter fa-2x"
    weight = 3
    url = "https://twitter.com/jsonbruce/"
[[params.social]]
    name="LinkedIn"
    icon = "fab fa-linkedin fa-2x"
    weight = 4
    url = "https://www.linkedin.com/in/xuhuan"

# Menu links
[[menu.main]]
    name = "Blog"
    weight = 1
    url  = "/posts/"
[[menu.main]]
    name = "About"
    weight = 2
    url = "/about/"
